# Generated by Django 5.1.2 on 2024-10-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_delete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='Sko_Adminside.category')),
            ],
        ),
        migrations.CreateModel(
            name='VariantOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('is_delete', models.BooleanField(default=False)),
                ('variants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Sko_Adminside.variants')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('qty_in_stock', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sko_Adminside.category')),
                ('varientoptions', models.ManyToManyField(related_name='products_variant_options', to='Sko_Adminside.variantoptions')),
                ('varients', models.ManyToManyField(related_name='products', to='Sko_Adminside.variants')),
            ],
        ),
    ]
