# Generated by Django 5.1.2 on 2024-10-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varientoptions',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Sko_Adminside.product')),
            ],
        ),
        migrations.DeleteModel(
            name='VariantOptions',
        ),
    ]
