# Generated by Django 5.1.2 on 2024-10-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varientoptions',
        ),
        migrations.DeleteModel(
            name='VariantOptions',
        ),
    ]
