# Generated by Django 5.1.2 on 2024-10-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0006_remove_product_sku_variantoptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varientoptions',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='varients',
        ),
        migrations.DeleteModel(
            name='VariantOptions',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
