# Generated by Django 5.1.2 on 2024-10-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0008_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_count',
            field=models.IntegerField(default=0),
        ),
    ]
