# Generated by Django 5.1.2 on 2024-10-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0010_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='brand',
        ),
    ]
