# Generated by Django 5.1.2 on 2024-10-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0014_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='brand',
        ),
    ]
