# Generated by Django 5.1.2 on 2024-10-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0015_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='brands/')),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
