# Generated by Django 5.1.2 on 2024-10-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0020_product_variant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_image',
        ),
        migrations.AddField(
            model_name='variants',
            name='variant_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Sko_Adminside.varientimage'),
        ),
    ]
