# Generated by Django 5.1.2 on 2024-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0021_remove_product_variant_image_variants_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varientimage',
            name='image',
            field=models.ImageField(upload_to='variant_images/'),
        ),
    ]
