# Generated by Django 5.1.2 on 2024-11-05 05:20

import Sko_Adminside.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0024_userprofile_bio_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[Sko_Adminside.models.validate_image]),
        ),
    ]
