# Generated by Django 5.1.2 on 2024-11-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0029_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
