# Generated by Django 5.1.2 on 2024-11-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0031_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_delete',
        ),
    ]
