# Generated by Django 5.1.2 on 2024-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0032_remove_cartitem_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
