# Generated by Django 5.1.2 on 2024-11-20 09:13

import User_side.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0039_alter_variants_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[User_side.utils.validate_phone]),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
                ('varients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whis_varient', to='Sko_Adminside.variants')),
            ],
            options={
                'unique_together': {('user', 'varients')},
            },
        ),
    ]
