# Generated by Django 5.1.2 on 2024-11-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0043_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
