# Generated by Django 5.1.2 on 2024-11-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0049_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sko_Adminside.coupon'),
        ),
    ]
