# Generated by Django 5.1.2 on 2024-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0053_remove_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('P', 'Product Offer'), ('C', 'Category Offer')], default='P', max_length=20),
        ),
    ]
