# Generated by Django 5.1.2 on 2024-11-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0057_cart_discounted_total_cartitem_discounted_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discounted_total',
        ),
    ]
