# Generated by Django 5.1.2 on 2024-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0058_remove_cartitem_discounted_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='Sko_Adminside.cartitem'),
        ),
    ]
