# Generated by Django 5.1.2 on 2024-11-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0061_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discounted_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
