# Generated by Django 5.1.2 on 2024-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sko_Adminside', '0066_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Refunded', 'Refunded'), ('Return Requested', 'Return Requested'), ('Return Rejected', 'Return Rejected'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
