from django.urls import path
from . import views

urlpatterns = [
    path('',views.user_sign,name='user_sign'),
    path('login/',views.user_login,name='user_login'),
    path('otp/',views.otp,name='otp'),
    path('resend_otp/',views.resend_otp,name='resend_otp'),
    path('home/',views.home,name='home'),
    path('product_list/',views.productlist,name='product_list'),
    path('forget_pass_email/',views.forget_pass_send_otp,name= 'forget_pass_send_otp'),
    path('pass_otp_validation',views.otp_pass_validation,name='otp_pass_validation'),
    path('reset_password/',views.reset_password,name='reset_password'),
    path('logout/', views.user_logout, name='user_logout'),
    path('product_view/<int:pk>/',views.product_view,name='product_view'),
    path('categoryview/<str:category_name>/', views.category_view, name='categoryview'),
    path('Userprofile/',views.Userprofile,name="Userprofile"),
    path('editprofile/',views.editprofile,name='editprofile'),
    path('address/',views.address,name='address'),   
    path('add_address',views.add_address,name='add_address'),
    path('delete_address/<int:pk>/', views.delete_address, name='delete_address'),
    path('change the password/',views.change_password,name='change_password'),
    path('edit_address/<int:pk>/',views.edit_address,name='edit_address'),
    path('change_password/',views.change_password,name='change_password'),
    path('delete_cart/<int:pk>/',views.delete_cart,name='delete_cart'),
    path('cart_view/',views.cart_view, name='cart_view'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('update-cart-item/', views.update_cart_item, name='update_cart_item'),
    path('checkout/',views.checkout,name='checkout'),
    path('set_primary_address/', views.set_primary_address, name='set_primary_address'),
    path('placeorder/',views.placeorder,name="placeorder"),
    path('userorders/',views.userorders,name='userorders'),
    path('cancel-order/<int:id>/', views.cancelorder, name='cancelorder'),
    path('return-order/<int:id>/', views.returnorder, name='returnorder'),
    path('wishlist/', views.wishlist,name='wishlist'),
    path('add_to_wishlist/',views.add_to_wishlist,name='add_to_wishlist'),
    path('delete_wishlist/<int:id>/',views.delete_wishlist,name='delete_wishlist'),
    
    
]
